/*
 * generated by Xtext
 */
package tum.ma.crudml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CrudmlUiModule extends tum.ma.crudml.ui.AbstractCrudmlUiModule {
	public CrudmlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
