/*
 * generated by Xtext
 */
package tum.ma.crudml.ui.contentassist

import tum.ma.crudml.ui.contentassist.AbstractCrudmlProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CrudmlProposalProvider extends AbstractCrudmlProposalProvider {
}
