/*
* generated by Xtext
*/
package tum.ma.crudml;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CrudmlStandaloneSetup extends CrudmlStandaloneSetupGenerated{

	public static void doSetup() {
		new CrudmlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

