/*
 * generated by Xtext
 */
package tum.ma.crudml;

import org.eclipse.xtext.generator.IOutputConfigurationProvider;

import tum.ma.crudml.generator.CustomOutputConfigurationProvider;

import com.google.inject.Binder;
import com.google.inject.Singleton;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class CrudmlRuntimeModule extends
		tum.ma.crudml.AbstractCrudmlRuntimeModule {

	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(IOutputConfigurationProvider.class)
				.to(CustomOutputConfigurationProvider.class)
				.in(Singleton.class);
	}
}
